service:
  name: ${self:custom.name}

frameworkVersion: ">=1.19.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: v1
  profile: my
  apiKeys:
    - ${self:custom.name}-${opt:stage}

custom:
  name: vuejs-pwa-and-ssr-on-lambda

package:
  include:
    - server/**/**.js
    - server/**/**.json
    - server/index.template.html
    - dist/**
  exclude:
    - node_modules/**
    - src/**
    - dev/**
    - server/**
    - local/**
    - config/**
    - .**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    - webpack.**.js


functions:
  render:
    handler: server/app.render
    timeout: 120
    memorySize: 128
    events:
      - http:
          path: '/'
          method: get
          private: true
      - http:
          path: '{proxy+}'
          method: get
          private: true
